### ISSUE TITLE
projects.ce.pdn.ac.lk related update requests

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/e17-co328-Greenhouse-Monitoring-System#99]
https://github.com/cepdnaclk/e17-co328-Greenhouse-Monitoring-System/blob/353cfd159e924af02ceb668a4da8fce5fdd8337c/docs/README.md?plain=1#L6-L7

Can you update this with your repository name?

---

You can use the following email here other than 'email@eng.pdn.ac.lk'
- prabhathg@gmail.com

https://github.com/cepdnaclk/e17-co328-Greenhouse-Monitoring-System/blob/353cfd159e924af02ceb668a4da8fce5fdd8337c/docs/data/index.json#L38

**Comment by VishvaNavanjana** [comment]
Issue Resolved
